name: epodx_dashboards
channels:
  - defaults
dependencies:
  - asn1crypto=0.23.0=py36h546eea3_0
  - ca-certificates=2017.08.26=h94faf87_0
  - certifi=2017.11.5=py36hb8ac631_0
  - cffi=1.11.2=py36h829d1a5_0
  - chardet=3.0.4=py36h420ce6e_1
  - cryptography=2.1.4=py36he1d7878_0
  - idna=2.6=py36h148d497_1
  - openssl=1.0.2n=h74b6da3_0
  - pip=9.0.1=py36h226ae91_4
  - pycparser=2.18=py36hd053e01_1
  - pyopenssl=17.5.0=py36h5b7d817_0
  - pysocks=1.6.7=py36h698d350_1
  - python=3.6.3=h3b118a2_4
  - requests=2.18.4=py36h4371aae_1
  - setuptools=36.5.0=py36h65f9e6e_0
  - six=1.11.0=py36h4db2310_1
  - urllib3=1.22=py36h276f60a_0
  - vc=14=h2379b0c_2
  - vs2015_runtime=14.0.25123=hd4c4e62_2
  - wheel=0.30.0=py36h6c3ec14_1
  - win_inet_pton=1.0.1=py36he67d7fd_1
  - wincertstore=0.2=py36h7fe50ca_0
  - pip:
    - google-api-python-client==1.6.4
    - httplib2==0.10.3
    - oauth2client==4.1.2
    - pyasn1==0.4.2
    - pyasn1-modules==0.2.1
    - rsa==3.4.2
    - uritemplate==3.0.0
prefix: C:\Users\mifryar\AppData\Local\conda\conda\envs\epodx_dashboards

